--계정생성
--CREAT USER 계정이름 identified BY 비밀번호;
CREATE USER test01 IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO test01;
REVOKE CONNECT FROM test01;

CREATE USER ddlexam IDENTIFIED BY 1111;--계정생성
GRANT CONNECT, RESOURCE TO ddlexam;--권한부여

--접속중인 계정은 삭제 불가능
--외래키 관계가 설정되어 있는 테이블은 삭제 불가능
DROP USER DDLEXAM;
DROP USER TEST01 CASCADE;--강제로 지우는 키

GRANT CREATE VIEW TO KH;

GRANT CREATE SYNONYM TO KH;

CREATE USER test00 IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO test00;

--공개동의어 생성
CREATE PUBLIC SYNONYM DEPT FOR KH.DEPARTMENT;
DROP PUBLIC SYNONYM DEPT;

--TEST00계정에 KH의 DEPARTMENT테이블 조회권한 부여
GRANT SELECT ON KH.DEPARTMENT TO test00;
GRANT SELECT ON KH.EMPLOYEE TO test00;

--실습
CREATE USER khtest IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO khtest;
GRANT CREATE VIEW TO khtest;
GRANT CREATE SYNONYM TO khtest;
-----
--DB계정생성
CREATE USER DBtest01 IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO DBtest01;

--0726
CREATE USER DBEXAM IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO DBEXAM;

--
CREATE USER jdbc IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO jdbc;

--
CREATE USER jdbcex IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO jdbcex;

--220201시험
CREATE USER oracleuser IDENTIFIED BY pwd1234;
GRANT CONNECT, RESOURCE TO oracleuser;