CREATE TABLE BRANDS(
    BRAND_ID  NUMBER PRIMARY KEY,
    BRAND_NAME  VARCHAR2(30) NOT NULL
);
CREATE SEQUENCE SEQ_BRAND_ID
START WITH 100
INCREMENT BY 100
MAXVALUE 1000
NOCYCLE
NOCACHE;

INSERT INTO BRANDS
VALUES(SEQ_BRAND_ID.NEXTVAL, 'Samsung');
INSERT INTO BRANDS
VALUES(SEQ_BRAND_ID.NEXTVAL, 'Apple');


CREATE TABLE PRODUCTS(
    PRODUCT_NO NUMBER PRIMARY KEY,
    PRODUCT_NAME  VARCHAR2(30) NOT NULL,
    PRODUCT_PRICE  NUMBER  NOT NULL,
    BRAND_CODE  NUMBER REFERENCES BRANDS(BRAND_ID),
    SERIAL_NO  VARCHAR2(50) UNIQUE,
    SOLD_OUT  CHAR(1) CHECK(SOLD_OUT IN ('Y','N'))
);
CREATE SEQUENCE PRODUCT_NO
START WITH 1
INCREMENT BY 1
MAXVALUE 10000
NOCYCLE
NOCACHE;

INSERT INTO PRODUCTS VALUES(PRODUCT_NO.NEXTVAL, '»ï¼º³ëÆ®ºÏ', 1800000, 100, 's-001','N');
INSERT INTO PRODUCTS VALUES(PRODUCT_NO.NEXTVAL, '°¶·°½Ã½º¸¶Æ®Æù', 1500000, 100, 's-002','N');
INSERT INTO PRODUCTS VALUES(PRODUCT_NO.NEXTVAL, '¸ÆºÏ', 2500000, 200, 'a-001','N');
INSERT INTO PRODUCTS VALUES(PRODUCT_NO.NEXTVAL, '¾ÆÀÌÆù', 1500000, 200, 'a-002','N');
INSERT INTO PRODUCTS VALUES(PRODUCT_NO.NEXTVAL, '¾ÆÀÌÆÐµå', 1000000, 200, 'a-003','N');
    
SELECT * FROM BRANDS;
SELECT * FROM PRODUCTS;

SELECT PRODUCT_NO, PRODUCT_NAME, BRAND_NAME, PRODUCT_PRICE, SERIAL_NO
FROM PRODUCTS
JOIN BRANDS ON (BRAND_CODE = BRAND_ID);