DROP TABLE MEMBER;
DROP TABLE BOARD;
DROP SEQUENCE MEMBER_NO;
DROP SEQUENCE BOARD_NO;
----------------------------------------
CREATE TABLE MEMBER (
    MEMBER_NO    NUMBER PRIMARY KEY,
    MEMBER_USERID   VARCHAR2(20) UNIQUE NOT NULL,
    MEMBER_USERPWD  CHAR(20)  NOT NULL,
    MEMBER_NICKNAME  VARCHAR2(20) UNIQUE NOT NULL,
    MEMBER_GENDER  VARCHAR2(3) CHECK(MEMBER_GENDER IN ('남', '여')) NOT NULL,
    MEMBER_EMAIL   VARCHAR2(30) NOT NULL
);
CREATE SEQUENCE MEMBER_NO
START WITH 1000
INCREMENT BY 1
MAXVALUE 1000000
NOCYCLE
NOCACHE;

INSERT INTO MEMBER VALUES(MEMBER_NO.NEXTVAL,'user01','1234','일일','여','Cbcd@naver.com');

DELETE FROM MEMBER WHERE MEMBER_NICKNAME='이이';

SELECT * FROM MEMBER;
CREATE TABLE BOARD (
    BOARD_NO   NUMBER  PRIMARY KEY,
    BOARD_TITLE  VARCHAR2(20)  NOT NULL,
    BOARD_CONTENT  VARCHAR2(200) NOT NULL ,
    BOARD_WRITEDATE  DATE   NOT NULL,
    BOARD_NICKNAME  VARCHAR2(20) NOT NULL,
    FOREIGN KEY(BOARD_NICKNAME) REFERENCES MEMBER(MEMBER_NICKNAME)ON DELETE SET NULL
);
CREATE SEQUENCE BOARD_NO
START WITH 1
INCREMENT BY 1
MAXVALUE 500000
NOCYCLE
NOCACHE;

INSERT INTO BOARD VALUES(BOARD_NO.NEXTVAL,'BN01','AAAABBBBCCCC',sysdate,'일일');
SELECT * FROM BOARD;

CREATE OR REPLACE VIEW MEMBER_VIEW--얕은복사개념
AS
SELECT MEMBER_NO, MEMBER_NICKNAME, MEMBER_EMAIL, BOARD_TITLE 
FROM MEMBER
JOIN BOARD ON (MEMBER_NICKNAME = BOARD_NICKNAME);

SELECT * FROM MEMBER_VIEW;

SELECT * FROM MEMBER;
SELECT * FROM M;
SELECT * FROM BOARD;
SELECT * FROM B;
CREATE SYNONYM M FOR MEMBER;
CREATE SYNONYM B FOR BOARD;

ALTER TABLE BOARD
MODIFY BOARD_NICKNAME NULL;
-------------------------------------------------------------------------
--2022-07-26 시험범위!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-------------------------------------



